# fly.toml app configuration file generated for weaverse-aspen-furniture on 2025-05-27T16:02:01+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weaverse-aspen-furniture'
primary_region = 'sin'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1024mb'
cpu_kind = 'shared'
cpus = 1
